import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const monumentGrotesk = localFont({
  src: [
    {
      path: "./fonts/MonumentGrotesk/MonumentGrotesk-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/MonumentGrotesk/MonumentGrotesk-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/MonumentGrotesk/MonumentGrotesk-Italic.ttf",
      weight: "400",//normal
      style: "italic",
    },
    {
      path: "./fonts/MonumentGrotesk/MonumentGrotesk-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/MonumentGrotesk/MonumentGrotesk-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/MonumentGrotesk/MonumentGrotesk-Mono.ttf",
      weight: "400", //normal
      style: "normal",
    },
    {
      path: "./fonts/MonumentGrotesk/MonumentGrotesk-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/MonumentGrotesk/MonumentGrotesk-Semi-Mono.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-monument-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={monumentGrotesk.variable}
      >
        {children}
      </body>
    </html>
  );
}
